
server:
  port: 80

management:
  endpoints:
    web:
      exposure:
        include:
        - info
        - health
        - prometheus

spring:
  mongodb:
    embedded:
      version: 3.5.5
  data:
    mongodb:
      database: test
      port: 27017

    #   database: test
      # uri : mongodb: //localhost:27017/test